---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: opensuse-leap-15

suites:
  - name: configure_ntp
    run_list:
      - recipe[ntp::default]
