name             'chrony'
maintainer       'mariadb-corporation'
maintainer_email 'evgeny.vlasov@fruct.org'
license          'All rights reserved'
description      'Installs/Configures chrony'
version          '0.1.0'
