AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 400

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
