#
# Config for Vagrant AWS access
#
aws:
   ami : 'ami-8cff51fb'			# AMI
   # subnet_id : 'subnet-xxx'		#
   access_key_id : 'xxxxxx' 		# insert your AWS access key id
   secret_access_key : 'xxxxxxx' 	# and secret access key
   keypair_name	: 'xxxxxxxxx' 		# your private key name
   security_groups : [ 'default', 'vagrant' ]
   region : 'eu-west-1'			# you AWS region
   pemfile : 'xxxxxxxxx.pem' 		# your private key
   user_data : "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"		# 
