#!/usr/bin/env ruby

require 'getoptlong'

require_relative 'core/help'
require_relative 'core/generators'
require_relative 'core/session'


puts 'MariaDb CI CLI'

#Reading options
opts = GetoptLong.new(
    ['--help', '-h', GetoptLong::NO_ARGUMENT],
    ['--template', '-t', GetoptLong::REQUIRED_ARGUMENT],
    ['--override', '-w', GetoptLong::NO_ARGUMENT],
)

session = Session.new

opts.each do |opt, arg|
  case opt
    when '--platforms'
      puts boxes.keys
    when '--template'
      if arg != ''
        session.configFile =arg
        puts 'Using template name '+session.configFile
      end
    when '--help'
      Help.display
      exit
    when '--override'
      session.isOverride =true
    else
      puts 'Option are not supported:'+opt
  end
end

=begin
  run command (create config only for now)
=end

session.checkConfig
session.loadCollections

cmd = ARGV.shift
case cmd
  when 'show'
    session.show(ARGV.shift)
  when 'setup'
    session.setup(ARGV.shift)
  else
    puts 'Something wrong with command line'
    Help.display
end


#  Help.display
#else
#
#  config = JSON.parse(IO.read(config_file))
#  Generator.generate(config,boxes.json)
#end


