---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: ubuntu-18.04
  - name: debian-9

suites:
  - name: configure_apt
    run_list:
      - recipe[packages::default]
