# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.box = "chef/ubuntu-12.04"
  #config.vm.box = "hashicorp/precise32" # x32
  #config.vm.box = "chef/fedora-21"
  #config.vm.box = "chef/opensuse-13.1"
  #config.vm.box = "chef/centos-6.6"
  #config.vm.box = "chef/centos-6.5-i386" # x32

  # configure Chef
  config.vm.provision "chef_solo" do |chef|
     chef.cookbooks_path = "../../../recipes/cookbooks"
     chef.roles_path = "."
     chef.add_role "test"
  end
 
end
