# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load AWS config file
if File.exist?("config/aws-config.yml")
  aws_config = YAML.load_file("config/aws-config.yml")["aws"]
  # pemfile = aws_config["pemfile"]
end

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "dummy"

  #config.ssh.pty = true	# tty, sudo
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  #config.vm.synced_folder ".", "/vagrant", disabled: true

  # RHEL 7 AMI
#  config.vm.provider :aws do |rhel7_aws, override|
#    rhel7_aws.access_key_id = aws_config["access_key_id"] # ENV['AWS_KEYID']
#    rhel7_aws.secret_access_key = aws_config["secret_access_key"] # ENV['AWS_SECRETKEY']
#    rhel7_aws.keypair_name = aws_config["keypair_name"] # ENV['AWS_KEYNAME']
#    rhel7_aws.ami = "ami-8cff51fb" # RHEL7
#    rhel7_aws.region = aws_config["region"]
#    rhel7_aws.instance_ready_timeout = 300
#    rhel7_aws.instance_type = "t2.micro"
#    rhel7_aws.security_groups = aws_config["security_groups"]
    
#    rhel7_aws.user_data = aws_config["user_data"]

#    override.vm.box = "dummy"
#    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
#    override.ssh.username = "ec2-user"
#    override.ssh.private_key_path = aws_config["pemfile"] # ENV['AWS_KEYPATH']
       
   # Chef
#  config.vm.provision "chef_solo" do |chef|
#    chef.cookbooks_path = "./recipes/cookbooks" # change path to mdbci/recipes/cookbooks
#    chef.roles_path = "."
#    chef.add_role "aws"
#    chef.synced_folder_type = 'rsync'
#  end
 
#  end


  # RHEL 6 AMI
#  config.vm.provider :aws do |rhel6_aws, override|
#    rhel6_aws.access_key_id = aws_config["access_key_id"]
#    rhel6_aws.secret_access_key = aws_config["secret_access_key"]
#    rhel6_aws.keypair_name = aws_config["keypair_name"]
#    rhel6_aws.ami = "ami-8cfc51fb"
#    rhel6_aws.region = aws_config["region"]
#    rhel6_aws.instance_type = "t2.micro"
#    rhel6_aws.security_groups = aws_config["security_groups"]

#    override.vm.box = "dummy"
#    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
#    override.ssh.username = "ec2-user"
#    override.ssh.private_key_path = aws_config["pemfile"]
    #
    # configure Chef
#    config.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "aws"
#    end
#  end

  # RHEL 5 AMI
#  config.vm.provider :aws do |rhel5_aws, override|
#    rhel5_aws.access_key_id = aws_config["access_key_id"]
#    rhel5_aws.secret_access_key = aws_config["secret_access_key"]
#    rhel5_aws.keypair_name = aws_config["keypair_name"]
#    rhel5_aws.ami = "ami-ea94369d"
#    rhel5_aws.region = aws_config["region"]
#    rhel5_aws.instance_type = "t2.micro"
#    rhel5_aws.security_groups = aws_config["security_groups"]

#    override.vm.box = "dummy"
#    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
#    override.ssh.username = "ec2-user"
#    override.ssh.private_key_path = aws_config["pemfile"]
    #
    # configure Chef
#    config.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "aws"
#    end
#  end

  # SLES 11 AMI
#  config.vm.provider :aws do |sles11_aws, override|
#    sles11_aws.access_key_id = aws_config["access_key_id"]
#    sles11_aws.secret_access_key = aws_config["secret_access_key"]
#    sles11_aws.keypair_name = aws_config["keypair_name"]
#    sles11_aws.ami = "ami-17c44860"
#    sles11_aws.region = "eu-west-1"
#    sles11_aws.instance_type = "t1.micro"
#    sles11_aws.security_groups = aws_config["security_groups"]

#    override.vm.box = "dummy"
#    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
#    override.ssh.username = "ec2-user"
#    override.ssh.private_key_path = aws_config["pemfile"]
    #
    # configure Chef
#    config.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "aws"
#    end
#  end

  # SLES 12 AMI
  config.vm.provider :aws do |sles12_aws, override|
    sles12_aws.access_key_id = aws_config["access_key_id"] # ENV['AWS_KEYID']
    sles12_aws.secret_access_key = aws_config["secret_access_key"] # ENV['AWS_SECRETKEY']
    sles12_aws.keypair_name = aws_config["keypair_name"] # ENV['AWS_KEYNAME']
    sles12_aws.ami = "ami-1804aa6f" # SLES12
    sles12_aws.region = aws_config["region"]
    sles12_aws.instance_ready_timeout = 300
    sles12_aws.instance_type = "t1.micro" # t1.micro
    sles12_aws.security_groups = aws_config["security_groups"]
    
    sles12_aws.user_data = aws_config["user_data"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = aws_config["pemfile"] # ENV['AWS_KEYPATH']

    # on this AMI couldn't install Chef, install by shell script 
    config.vm.provision :shell, :path => "./curl_install.sh", privileged: true
    config.vm.provision :shell, :path => "./chef_install.sh", privileged: true

    # Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "./recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
      chef.synced_folder_type = 'rsync'
    end

  end

  

end
