# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #config.vm.box = "dummy"
  #config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # RHEL 7 AMI
  config.vm.provider :aws do |rhel7_aws, override|
    rhel7_aws.access_key_id = ENV['AWS_KEYID']
    rhel7_aws.secret_access_key = ENV['AWS_SECRETKEY']
    rhel7_aws.keypair_name = ENV['AWS_KEYNAME']
    rhel7_aws.ami = "ami-8cff51fb"	# ubuntu: "ami-a7fdfee2"
    rhel7_aws.region = "eu-west-1"
    rhel7_aws.instance_type = "t2.micro"
    rhel7_aws.security_groups = ["default"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu" # ???
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    #
    # configure Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
    end
  end

  # RHEL 6 AMI
  config.vm.provider :aws do |rhel6_aws, override|
    rhel6_aws.access_key_id = ENV['AWS_KEYID']
    rhel6_aws.secret_access_key = ENV['AWS_SECRETKEY']
    rhel6_aws.keypair_name = ENV['AWS_KEYNAME']
    rhel6_aws.ami = "ami-8cfc51fb"	# ubuntu: "ami-a7fdfee2"
    rhel6_aws.region = "eu-west-1"
    rhel6_aws.instance_type = "t2.micro"
    rhel6_aws.security_groups = ["default"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu" # ???
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    #
    # configure Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
    end
  end

  # RHEL 5 AMI
  config.vm.provider :aws do |rhel5_aws, override|
    rhel5_aws.access_key_id = ENV['AWS_KEYID']
    rhel5_aws.secret_access_key = ENV['AWS_SECRETKEY']
    rhel5_aws.keypair_name = ENV['AWS_KEYNAME']
    rhel5_aws.ami = "ami-ea94369d"	# ubuntu: "ami-a7fdfee2"
    rhel5_aws.region = "eu-west-1"
    rhel5_aws.instance_type = "t2.micro"
    rhel5_aws.security_groups = ["default"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu" # ???
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    #
    # configure Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
    end
  end

  # SLES 11 AMI
  config.vm.provider :aws do |sles11_aws, override|
    sles11_aws.access_key_id = ENV['AWS_KEYID']
    sles11_aws.secret_access_key = ENV['AWS_SECRETKEY']
    sles11_aws.keypair_name = ENV['AWS_KEYNAME']
    sles11_aws.ami = "ami-17c44860"	# ubuntu: "ami-a7fdfee2"
    sles11_aws.region = "eu-west-1"
    sles11_aws.instance_type = "t2.micro"
    sles11_aws.security_groups = ["default"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu" # ???
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    #
    # configure Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
    end
  end

  # SLES 12 AMI
  config.vm.provider :aws do |sles12_aws, override|
    sles12_aws.access_key_id = ENV['AWS_KEYID']
    sles12_aws.secret_access_key = ENV['AWS_SECRETKEY']
    sles12_aws.keypair_name = ENV['AWS_KEYNAME']
    sles12_aws.ami = "ami-1804aa6f"	# ubuntu: "ami-a7fdfee2"
    sles12_aws.region = "eu-west-1"
    sles12_aws.instance_type = "t2.micro"
    sles12_aws.security_groups = ["default"]

    override.vm.box = "dummy"
    override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    override.ssh.username = "ubuntu" # ???
    override.ssh.private_key_path = ENV['AWS_KEYPATH']
    #
    # configure Chef
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "aws"
    end
  end

end
