#
# Config for Vagrant AWS access
#

aws:
   # ami : 'ami-8cff51fb'
   # subnet_id : 'subnet-xxx'
   access_key_id : 'xxxxxx' # insert your AWS access key id
   secret_access_key : 'xxxxxxx' # and secret access key
   keypair_name	: 'h05t-key-pair-eu-west1'
   security_groups : [ 'default', 'vagrant' ]
   region : 'eu-west-1'
   pemfile : 'h05t-key-pair-eu-west1.pem'
   user_data : "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"
