# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	#config.vm.box = "base"
	#config.vm.synced_folder "provision/master/", "provision/slave/" 

	# master vm
	config.vm.define "master" do |master|
    		master.vm.box = "hashicorp/precise32"
		#master.vm.box = "precise32_x32"	
		#master.vm.box_url = "http://files.vagrantup.com/precise32.box"
    		master.vm.hostname = "master"
    		#master.vm.network "forwarded_port", guest: 3306, host: 3336
    		master.vm.network "private_network", ip: "192.168.1.101"

		#master.vm.synced_folder '/provision/master'

    		# Chef provision for 'master' node, need > 12.3.0
    		master.vm.provision "chef_solo" do |chef|
			#chef.cookbooks_path = "recipes/cookbooks"
      			chef.cookbooks_path = "../../../recipes/cookbooks"
      			chef.roles_path = "recipes/roles"
      			chef.add_role "common"
		end
		
		master.vm.provision :shell, :path => "./master_repl.sh", privileged: true

  	end

  	# slave VM
	config.vm.define "slave" do |slave|
		slave.vm.box = "hashicorp/precise32"
		#slave.vm.box = "precise32_x32"	
		#slave.vm.box_url = "http://files.vagrantup.com/precise32.box"
		slave.vm.hostname = "slave"
    		#slave.vm.network "forwarded_port", guest: 3306, host: 3337
		slave.vm.network "private_network", ip: "192.168.1.102"

		#slave.vm.synced_folder "/provision/slave"

		# Chef provision for 'slave' node, need > 12.3.0
    		slave.vm.provision "chef_solo" do |chef|
      			chef.cookbooks_path = "../../../recipes/cookbooks"
			#chef.cookbooks_path = "/recipes/cookbooks"
      			chef.roles_path = "recipes/roles"
      			chef.add_role "common"
		end

		slave.vm.provision :shell, :path => "./slave_repl.sh", privileged: true

	end   

end
