---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: install
    run_list:
      - recipe[mariadb_columnstore::install]
  - name: configure_repository
    run_list:
      - recipe[mariadb_columnstore::configure_repository]
