# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  # ubuntu 12.04
  #config.vm.box = "hashicorp/precise32"
  #config.vm.box_url = "https://vagrantcloud.com/hashicorp/boxes/precise32/versions/1.0.0/providers/virtualbox.box"

  # fedora
  config.vm.box = "chef/fedora-21"
  #config.vm.box_url = "https://atlas.hashicorp.com/chef/boxes/fedora-21/versions/1.0.0/providers/virtualbox.box"


  # configure Chef
  config.vm.provision "chef_solo" do |chef|
     chef.cookbooks_path = "../../../recipes/cookbooks"
     chef.roles_path = "."
     chef.add_role "test"
  end
 
end
