# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  #config.vm.box = "base"

  config.vm.define "master" do |master|
    master.vm.box = "hashicorp/precise32"	# ubuntu 12.04 x32
    #master.vm.box = "chef/ubuntu-14.04"	# x64
    #master.vm.box = "chef/ubuntu-14.10"	# x64
    #master.vm.box = "chef/ubuntu-12.04"	# x64
    
    master.vm.hostname = "master"
    #master.vm.network "forwarded_port", guest: 3306, host: 3336
    master.vm.network "private_network", ip: "192.168.2.1"

    # Chef provision for 'master' node
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = ["../../../recipes/cookbooks", "recipes/cookbooks" ]
      chef.roles_path = "recipes/roles"
      chef.add_role "master"

    #  chef.json = {
    #    "mysql" => {
    #    	"server_root_password" => "qwerty",           
    #    	"server_repl_password" => "qwerty",
    #    	"server_debian_password" => "qwerty"
    #    }
    #  }
    
    end
  end

  # slave VM
#  config.vm.define "slave" do |slave|
#    slave.vm.box = "hashicorp/precise32"
#    slave.vm.hostname = "slave"
#    slave.vm.network "forwarded_port", guest: 3306, host: 3337
#    slave.vm.network "private_network", ip: "192.168.2.2"

#   Chef provision for 'slave' node
#    config.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "recipes/cookbooks"
#      chef.roles_path = "recipes/roles"
#      chef.add_role "slave"
#    end
#  end

end
