name              'galera'
maintainer        'OSLL'
maintainer_email  'kirill.krinkin@gmail.com'
license           'Apache 2.0'
description       'Galera coockbook'
version           '0.0.1'
recipe            'install', 'Installs Enterprise edition'
recipe            'uninstall', 'Uninstalls any edition'
recipe            'start', 'Creates new instance of service and starts it'
depends           'ntp'

supports          'redhat'
supports          'centos'
supports          'fedora'
supports          'debian'
supports          'ubuntu'
supports          'suse'

