# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
#Check if you have the good Vagrant version to use docker provider...
Vagrant.require_version ">= 1.6.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

#  config.ssh.username = 'root'
  config.ssh.port = 22

  config.vm.synced_folder "cnf/", "/home/vagrant/cnf_templates"

#  config.vm.network :forwarded_port, host: 3306, guest: 3306

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
#    d.ports = ["3306:3306"]
    d.privileged = true
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../../../recipes/cookbooks"
    chef.roles_path = "."
    chef.add_role "docker"
  end

end
