# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
#VAGRANTFILE_API_VERSION = "2"
#Check if you have the good Vagrant version to use docker provider...
#Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|

#  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

  #config.ssh.port = 22
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "cnf/", "/home/vagrant/cnf_templates"

  config.vm.network "private_network", type: "dhcp"

#  config.vm.network :forwarded_port, host: 3306, guest: 3306

  # install Chef via plugin
#  config.omnibus.chef_version = "12.5.1"

  # node0 - Ubuntu 14.04 -- WORKS!
#  config.vm.define "node0" do |node0|  
#    node0.vm.provider "docker" do |d|
#      d.build_dir = "ubuntu/"
#      d.has_ssh = true
#      #d.ports = ["3306:3306"]
#      d.privileged = true
#      #d.remains_running = false
#    end    

#    node0.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker0"
#    end
#  end

  # node1 - CentOS 6.7
  config.vm.define "node1" do |node1|
    node1.vm.provider "docker" do |d|
      d.build_dir = "centos/"
      d.has_ssh = true
      #d.ports = ["3306:3306"]
      d.privileged = true
      #d.remains_running = false
    end    

    node1.vm.provision "shell", path: "./install_recipe.sh"
    
    # hack 
#    node1.vm.provision :shell do |sh|
#      sh.inline = "#!/bin/bash 
#        export PATH=$PATH:/opt/chef/bin:/opt/chef/embedded/bin"
#      sh.privileged = true
#    end

#    node1.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker1"
#    end

  end

  # node2 - OpenSuSE 13
#  config.vm.define "node2" do |node2|
#    node2.vm.provider "docker" do |d|
#      d.build_dir = "sles/"
#      d.has_ssh = true
#      #d.ports = ["3306:3306"]
#      d.privileged = true
#    end    

#    node2.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker2"
#    end
#  end
  
end
