# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
#VAGRANTFILE_API_VERSION = "2"
#Check if you have the good Vagrant version to use docker provider...
#Vagrant.require_version ">= 1.6.0"

Vagrant.configure("2") do |config|

#  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

  config.vm.synced_folder "cnf/", "/home/vagrant/cnf_templates"

  config.vm.network "private_network", type: "dhcp"

  # node000 - Ubuntu 14.04
#  config.vm.define "node000" do |node000|  
#    node000.vm.provider "docker" do |d|
#      d.build_dir = "ubuntu/"
#      d.has_ssh = true
#      #d.ports = ["3306:3306"]
#      d.privileged = true
#      #d.remains_running = false
#    end    

#    node000.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker0"
#    end
#  end


  # node001 - CentOS 6.7
#  config.vm.define "node001" do |node001|
#    node001.vm.provider "docker" do |d|
#      d.build_dir = "centos6.7/"
#      d.has_ssh = true
#      #d.ports = ["3306:3306"]
#      d.privileged = true
#    end    

#    node001.vm.provision "shell", path: "./install_recipe.sh"
    
#    node001.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker1"
#    end
#  end


  # node002 - CentOS 7
  config.vm.define "node002" do |node002|
    node002.vm.provider "docker" do |d|
      d.build_dir = "centos7/"
      d.has_ssh = true
      #d.ports = ["3306:3306"]
      d.privileged = true
    end    
    
    node002.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../../../../recipes/cookbooks"
      chef.roles_path = "."
      chef.add_role "docker2"
    end

  end

  # TODO 6539: fix chef-container
  # node003 - OpenSuSE 13
#  config.vm.define "node003" do |node003|
#    node003.vm.provider "docker" do |d|
#      d.build_dir = "sles/"
#      d.has_ssh = true
#      #d.ports = ["3306:3306"]
#      d.privileged = true
#    end    

#    node003.vm.provision "shell", path: "./install_recipe.sh"
    
#    node003.vm.provision "chef_solo" do |chef|
#      chef.cookbooks_path = "../../../../recipes/cookbooks"
#      chef.roles_path = "."
#      chef.add_role "docker3"
#    end

#  end    

end
